import 'package:bloc_project/core/theme/app_pallete.dart';
import 'package:bloc_project/dependencies/dependescies_imports.dart';
import 'package:bloc_project/features/doctor/presentation/widgets/dropdown_bar.dart';
import 'package:bloc_project/features/patient/data/model/appointment_booking_model.dart';
import 'package:bloc_project/features/patient/data/model/available_slot_model.dart';
import 'package:bloc_project/features/patient/data/model/doctor_model.dart';
import 'package:bloc_project/features/patient/domain/usecases/book_appoitment_usecase.dart';
import 'package:bloc_project/features/patient/domain/usecases/get_available_slots_usecase.dart';
import 'package:bloc_project/features/patient/domain/usecases/get_all_doctor_usecase.dart';
import 'package:bloc_project/features/patient/presentation/blocs/doctor_details/bloc/doctor_details_bloc.dart';
import 'package:bloc_project/utils/setuplogger.dart';
// import 'package:bloc_project/features/patient/presentation/blocs/doctor_bloc/bloc/doctor_bloc.dart';
// import 'package:bloc_project/features/patient/presentation/blocs/doctor_bloc/bloc/doctor_event.dart';
// import 'package:bloc_project/features/patient/presentation/blocs/doctor_bloc/bloc/doctor_state.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_rating_bar/flutter_rating_bar.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:velocity_x/velocity_x.dart';
import '../../../payment/pages/payment_screen.dart';
part 'appointment_details.dart';
part 'available_slots.dart';
//part 'doctor_details_cart.dart';
part 'doctor_info_row.dart';
