// import 'package:bloc_project/core/theme/app_pallete.dart';
// import 'package:bloc_project/features/doctor/data/remote_datasource/patient_remote_datasource.dart';
// import 'package:bloc_project/features/doctor/data/repositories/patient_repoImpl.dart';
// import 'package:bloc_project/features/doctor/domain/repositories/patient_repository.dart';
// import 'package:bloc_project/features/doctor/presentation/blocs/PatientDetails/bloc/patientdetail_bloc.dart';
// import 'package:bloc_project/features/doctor/presentation/widgets/dropdown_bar.dart';
// import 'package:flutter/material.dart';
// import 'package:flutter_bloc/flutter_bloc.dart';
// import 'package:http/http.dart' as http;
// part 'patient_details_android.dart';
// part 'patient_details.dart';
